name: "next lintをかける"

on:
  pull_request:
    paths:
      - "**/*.ts"
      - "**/*.tsx"

jobs:
  nextlint:
    runs-on: ubuntu-latest
    steps:
      - name: "checkoutする"
        uses: actions/checkout@v4

      - name: "Node.jsのセットアップ"
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "pnpmのセットアップ"
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: "reviewdogのインストール"
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: "pnpmのパッケージ保存先を保持"
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: "キャッシュを使う"
        uses: actions/cache@v4
        id: pnpm-cache-node_modules
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: "パッケージのインストール"
        run: pnpm install

      - name: "next lintの実行 with reviewdog"
        run: |
          pnpm run lint -f checkstyle | reviewdog -f checkstyle --name=nextlint -reporter=github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

